#!/usr/bin/env ruby

def has_required_version? actual_version, required_version
  Gem::Requirement.new(required_version).satisfied_by? Gem::Version.new(actual_version)
end

def find_version(lib_name, version_placement)
  `#{lib_name} --version`.match(/(\d+)\.(\d+)\.(\d+)/)[0]
end

def confirm lib_name, required_version, version_placement=2
  actual_version = find_version(lib_name, version_placement)
  if has_required_version? actual_version, required_version
    puts "OK - #{lib_name} #{actual_version} #{required_version}"
  else
    puts "ERR - please install #{lib_name} #{required_version}"
  end
end

confirm "ruby", ">= 2.0.0"
confirm "redis-cli", ">= 2.4.11"

if confirm "psql", ">= 9.2.0", 3
  if `echo "select 1" | psql -At postgres`.strip == "1"
    puts "OK - postgres 9.2.0 up and running"
  else
    puts "ERR - postgres isn't running"
  end
end
