#!/usr/bin/env ruby

def has_required_version? actual_version, required_version
  Gem::Requirement.new(required_version).satisfied_by? Gem::Version.new(actual_version)
end

def find_version(lib_name, version_placement)
  output = `#{lib_name} --version`.split("\n")[0].split(' ')
  output.length > 1 ? output[version_placement].strip : ""
end

def confirm lib_name, required_version, version_placement=-1
  actual_version = find_version(lib_name, version_placement)

  if has_required_version? actual_version, required_version
    puts "OK - #{lib_name} #{actual_version} #{required_version}"
  else
    puts "ERR - please install #{lib_name} #{required_version}"
  end
end

confirm "ruby", "= 1.9.3p125", 1
confirm "redis-cli", ">= 2.4.11"

if confirm "psql", ">= 9.1.3"
  if `echo "select 1" | psql -At postgres`.strip == "1"
    puts "OK - postgres 9.1.3 up and running"
  else
    puts "ERR - postgres isn't running"
  end
end
